### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [irbis-labs/rsmorphy#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by alexander-irbis** [comment]
Hi! 
Thank you for reminding.
It was just an old code, which I have not yet had time to update.

But, speaking not about rsmorphy, there is an important dependency in my projects (unpublished yet) that still pulls for itself rustc-serialize: [docopt](https://crates.io/crates/docopt)
